source 'https://rubygems.org'
source 'https://wallarm.jfrog.io/wallarm/api/gems/gems'
source 'https://wallarm.jfrog.io/wallarm/api/gems/gems-dev'

# Specify your gem's dependencies in scanner_extensions.gemspec
gemspec
