FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.3

ADD  ./elastic/wait-for-it.sh ./elastic/es.sh /tmp/
COPY elastic/elasticsearch.yml /usr/share/elasticsearch/config/
EXPOSE 9200

RUN /tmp/es.sh
